import{a as d,S as u}from"./assets/vendor-db58f109.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerpolicy&&(a.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?a.credentials="include":e.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();d.defaults.headers.common["x-api-key"]="live_BGHVXS9HRJW6rgW9IQYtalpwpiOTRRwNlGFWeCidmk1cMnZOsP2CCA8I8oCDINU9";const c=(t,r)=>{t&&r?(t.textContent="Oops! Something went wrong! Try reloading the page!",t.style.display="block",r.style.display="none"):console.error("Error element or loader is not defined.")},p=(t,r)=>d.get("https://api.thecatapi.com/v1/breeds").then(o=>{if(!o.data||o.data.length===0)throw new Error("No breeds data found");return o.data}).catch(o=>{c(t,r),console.error(o)}),f=(t,r,o)=>d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${t}`).then(n=>{if(!n.data||n.data.length===0)throw new Error(`No cat found for breed ID: ${t}`);return n.data}).catch(n=>{c(r,o),console.error(n)});let s=null,l=null;function m(t){return t.map(r=>{const{name:o,description:n,temperament:e}=r.breeds[0];return`
        <div class="cat-card">
          <img class="cat-img" src="${r.url}" alt="${o}">
          <div>
            <h2>${o}</h2>
            <p><span class="text-bold">Description:</span> ${n}</p>
            <p><span class="text-bold">Temperament:</span> ${e}</p>
          </div>
        </div>
      `}).join("")}document.addEventListener("DOMContentLoaded",()=>{s=document.querySelector(".error"),l=document.querySelector(".loader");const t=document.querySelector(".breed-select"),r=document.querySelector(".cat-info");l.style.display="block",p(s,l).then(o=>{o.forEach(n=>{const e=document.createElement("option");e.value=n.id,e.textContent=n.name,t.appendChild(e)}),new u({select:t}),t.style.display="block",l.style.display="none",s.style.display="none"}).catch(()=>{c(s,l)}),t.addEventListener("change",o=>{l.style.display="block",s.style.display="none",r.innerHTML="",f(o.target.value,s,l).then(n=>{const e=m(n);r.innerHTML=e,l.style.display="none"}).catch(()=>{c(s,l)})})});
//# sourceMappingURL=commonHelpers.js.map
