import{a as l,S as i}from"./assets/vendor-db58f109.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&s(o)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();l.defaults.headers.common["x-api-key"]="live_BGHVXS9HRJW6rgW9IQYtalpwpiOTRRwNlGFWeCidmk1cMnZOsP2CCA8I8oCDINU9";function a(){errorElement.textContent="Oops! Something went wrong! Try reloading the page!",errorElement.style.display="block",breedSelect.style.display="none",loader.style.display="none"}const d=()=>l.get("https://api.thecatapi.com/v1/breeds").then(n=>n.data).catch(n=>{a(),console.error(n)}),p=n=>l.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${n}`).then(r=>r.data).catch(r=>{a(),console.error(r)});function u(n){return n.map(r=>{const{name:c,description:s,temperament:e}=r.breeds[0];return`
        <div class="cat-card">
          <img class="cat-img" src="${r.url}" alt="${c}">
          <div>
            <h2>${c}</h2>
            <p><span class="text-bold">Description:</span> ${s}</p>
            <p><span class="text-bold">Temperament:</span> ${e}</p>
          </div>
        </div>
      `}).join("")}document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".breed-select"),r=document.querySelector(".loader"),c=document.querySelector(".error"),s=document.querySelector(".cat-info");c.style.display="none",d().then(e=>{e.forEach(t=>{const o=document.createElement("option");o.value=t.id,o.textContent=t.name,n.appendChild(o)}),new i({select:n}),r.style.display="none"}).catch(()=>a()),n.addEventListener("change",e=>{r.style.display="block",s.innerHTML="",p(e.target.value).then(t=>{const o=u(t);s.innerHTML=o,r.style.display="none"}).catch(()=>a())})});
//# sourceMappingURL=commonHelpers.js.map
